### ISSUE TITLE
Have you ever compiled LiftDragPlugin ?

### ISSUE THREAD

**Issue by PeterBorisenko** [SwiftGust/ardupilot_gazebo#46]
The bracket at the end of class definition in `LiftDragPlugin.hh` is not closed.
Also there are many class members absent (e.g. link, cma, etc.)

**Comment by SwiftGust** [comment]
LiftDrag Plugin is no needs to be compiled from this repository since it is part of official gazebo plugin.
LiftDrag Plugin code is just there untouched and not compiled at all as stated in [CMakeList.txt]
(https://github.com/SwiftGust/ardupilot_gazebo/blob/master/CMakeLists.txt)
May needs to be removed.
